# Generated by Django 4.0.3 on 2022-05-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('obj_type', models.CharField(choices=[('web_studio', 'Веб-студия'), ('freelance', 'Фриланс')], max_length=60, verbose_name='Тип')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=300, null=True, verbose_name='Цель')),
                ('target_type', models.CharField(choices=[('commerce', 'Коммерческая'), ('non_commerce', 'Некоммерческая')], max_length=60, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория инструмент для создания сайта',
                'verbose_name_plural': 'Категории инструментов для создания сайта',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tool_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('logo', models.ImageField(blank=True, default='', upload_to='tool_logos')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('foundation_year', models.IntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='webstart.toolcategory', verbose_name='Относится к категории')),
            ],
            options={
                'verbose_name': 'Инструмент для создания сайта',
                'verbose_name_plural': 'Инструменты для создания сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Лендинг', 'Лендинг'), ('Интернет-магазин', 'Интернет-магазин'), ('Корпоративный имеджевый сайт', 'Корпоративный имеджевый сайт'), ('Корпоративный портал', 'Корпоративный портал'), ('Промо-сайт', 'Промо-сайт'), ('Веб-сервис', 'Веб-сервис'), ('Форум', 'Форум'), ('Блог', 'Блог')], max_length=60, unique=True, verbose_name='Тип')),
                ('for_targets', models.ManyToManyField(blank=True, to='webstart.target', verbose_name='Для целей')),
            ],
            options={
                'verbose_name': 'Тип сайта',
                'verbose_name_plural': 'Типы сайтов',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(blank=True, null=True, verbose_name='Минимальная цена')),
                ('max_price', models.IntegerField(blank=True, null=True, verbose_name='Максимальная цена')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='webstart.object', verbose_name='Относится к объекту')),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='webstart.sitetype', verbose_name='Относится к типу сайта')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'unique_together': {('obj', 'site_type')},
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webstart.object', verbose_name='Относится к объекту')),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, default='', upload_to='web_studio_logos')),
                ('projects', models.ManyToManyField(blank=True, to='webstart.sitetype', verbose_name='Типы сайтов')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webstart.tool', verbose_name='Относится к иснтрументу')),
                ('has_free', models.BooleanField(default=False, verbose_name='Имеет бесплатный тариф')),
                ('free_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бесплатный период')),
                ('min_price_for_month', models.IntegerField(blank=True, null=True, verbose_name='Минимальная цена за месяц')),
                ('max_price_for_month', models.IntegerField(blank=True, null=True, verbose_name='Максимальная цена за месяц')),
                ('constructor_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('site_types', models.ManyToManyField(blank=True, to='webstart.sitetype', verbose_name='Можно реализовать')),
            ],
            options={
                'verbose_name': 'Конструктор',
                'verbose_name_plural': 'Конструкторы',
            },
        ),
    ]
