# Generated by Django 4.0.3 on 2022-05-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetype',
            name='for_targets',
        ),
    ]
