# Generated by Django 4.0.3 on 2022-05-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='site_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='webstart.sitetype', verbose_name='Относится к типу сайта'),
        ),
    ]
