# Generated by Django 4.0.3 on 2022-05-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webstudio',
            old_name='site_type',
            new_name='projects',
        ),
    ]
