# Generated by Django 4.0.3 on 2022-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0002_remove_sitetype_for_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetype',
            name='for_targets',
            field=models.ManyToManyField(blank=True, to='webstart.target', verbose_name='Для целей'),
        ),
    ]
