# Generated by Django 4.0.3 on 2022-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0002_alter_price_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
    ]
