# Generated by Django 4.0.3 on 2022-05-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0003_contractor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='price',
        ),
    ]
