# Generated by Django 4.0.3 on 2022-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0003_sitetype_for_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
