# Generated by Django 4.0.3 on 2022-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0004_sitetype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Способ реализации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ реализации',
                'verbose_name_plural': 'Способы реализации',
            },
        ),
    ]
