# Generated by Django 4.0.3 on 2022-05-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0004_remove_contractor_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('obj', 'site_type')},
        ),
    ]
