# Generated by Django 4.0.3 on 2022-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0005_implementationway'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationway',
            name='implementation_type',
            field=models.CharField(blank=True, choices=[('self_implementation', 'Самостоятельно'), ('non_self', 'Не самостоятельно')], max_length=60, null=True, verbose_name='Тип'),
        ),
    ]
