# Generated by Django 4.0.3 on 2022-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0005_alter_price_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
