# Generated by Django 4.0.3 on 2022-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0006_alter_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AddField(
            model_name='price',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная цена'),
        ),
    ]
