# Generated by Django 4.0.3 on 2022-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0006_implementationway_implementation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationway',
            name='implementation_type',
            field=models.CharField(blank=True, choices=[('self_implementation', 'Самостоятельно'), ('to_order', 'На заказ')], max_length=60, null=True, verbose_name='Тип'),
        ),
    ]
