# Generated by Django 4.0.3 on 2022-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0007_alter_implementationway_implementation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationway',
            name='implementation_type',
            field=models.CharField(blank=True, choices=[('Самостоятельно', 'Самостоятельно'), ('На заказ', 'На заказ')], max_length=60, null=True, verbose_name='Тип'),
        ),
    ]
