# Generated by Django 4.0.3 on 2022-05-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0007_remove_price_price_price_max_price_price_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='max_price',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='min_price',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Минимальная цена'),
        ),
    ]
