# Generated by Django 4.0.3 on 2022-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0008_alter_implementationway_implementation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='site_types',
            field=models.ManyToManyField(blank=True, null=True, to='webstart.sitetype', verbose_name='Можно реализовать'),
        ),
    ]
