# Generated by Django 4.0.3 on 2022-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0008_alter_price_max_price_alter_price_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
    ]
