# Generated by Django 4.0.3 on 2022-05-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0010_alter_contractor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Телефон'),
        ),
    ]
