# Generated by Django 4.0.3 on 2022-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0010_constructor_template_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='auto_sitemap_and_robots',
            field=models.BooleanField(default=False, verbose_name='Автоматически формируются Sitemap и Robots'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='has_free_ssl_certificate',
            field=models.BooleanField(default=False, verbose_name='АБесплатный SSL сертификат'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='has_mobile_version_editor',
            field=models.BooleanField(default=False, verbose_name='Есть редактор мобильной версии сайта'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='has_seo_setting_master',
            field=models.BooleanField(default=False, verbose_name='Есть мастер для настройки SEO'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='is_all_templates_responsive',
            field=models.BooleanField(default=False, verbose_name='Все шаблоны адаптивны'),
        ),
    ]
