# Generated by Django 4.0.3 on 2022-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0011_constructor_auto_sitemap_and_robots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='has_free_ssl_certificate',
            field=models.BooleanField(default=False, verbose_name='Бесплатный SSL сертификат'),
        ),
    ]
