# Generated by Django 4.0.3 on 2022-05-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstart', '0011_alter_contractor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная цена'),
        ),
    ]
